public enum Tarifas {
    IPVA_CAMINHAO("IPVA CAMINHAO",0.01d),
    SEGURO_CAMINHAO("SEGURO CAMINHAO",0.02d),
    DIST_VISTORIA_CAMINHAO("DIST_VISTORIA CAMINHAO",30000d),
    PRECO_VISTORIA_CAMINHAO("PRECO_VISTORIA CAMINHAO",1000d),
    DIST_MANUTENCAO_CAMINHAO("DIST_MANUTENCAO CAMINHAO",20000d),
    PRECO_MANUTENCAO_CAMINHAO("PRECO_MANUTENCAO CAMINHAO",1000d),
    TAXA_CAMINHAO("TAXA CAMINHAO",2000d),

    IPVA_CARRO("IPVA CARRO",0.04d),
    SEGURO_CARRO("SEGURO CARRO",0.05d),
    DIST_ALINHAMENTO_CARRO("DIST_ALINHAMENTO CARRO",10000d),
    PRECO_ALINHAMENTO_CARRO("PRECO_ALINHAMENTO CARRO",80d),
    TAXA_CARRO("TAXA CARRO",300d),

    IPVA_FURGAO("IPVA FURGAO",0.03d),
    SEGURO_FURGAO("SEGURO FURGAO",0.03d),
    DIST_ALINHAMENTO_FURGAO("DIST_ALINHAMENTO FURGAO",10000d),
    PRECO_ALINHAMENTO_FURGAO("PRECO_ALINHAMENTO FURGAO",120d),
    DIST_VISTORIA_FURGAO("DIST_VISTORIA FURGAO",10000d),
    PRECO_VISTORIA_FURGAO("PRECO_VISTORIA FURGAO",500d),

    IPVA_VAN("IPVA VAN",0.03d),
    SEGURO_VAN("SEGURO VAN",0.03d),
    DIST_ALINHAMENTO_VAN("DIST_ALINHAMENTO VAN",10000d),
    PRECO_ALINHAMENTO_VAN("PRECO_ALINHAMENTO VAN",120d),
    DIST_VISTORIA_VAN("DIST_VISTORIA VAN",10000d),
    PRECO_VISTORIA_VAN("PRECO_VISTORIA VAN",500d);

    String descricao;
    double valor;

    Tarifas(String desc, double valor){
        if(valor < 1){valor = 1d;}
        this.descricao = desc;
        this.valor = valor;
    }

    public double getValor() {
        return valor;
    }

    public String getDescricao() {
        return descricao;
    }
}
